# Generated by Django 5.2.17 on 2026-09-28 05:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('PAYMENT_DUE', 'Payment Due'), ('TRANSFER_SUCCESS', 'Transfer Successful'), ('LOAN_UPDATE', 'Loan Application Update'), ('SECURITY', 'Security Alert'), ('SYSTEM', 'System Notice')], db_index=True, default='SYSTEM', max_length=25)),
                ('link', models.CharField(blank=True, max_length=120)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'finova_notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
