# Generated by Django 5.2.17 on 2026-09-29 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='kyc_status',
            field=models.CharField(choices=[('PENDING', 'Pending Verification'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('NEEDS_REVIEW', 'Needs Review')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='KYCRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(db_index=True, help_text='Unique KYC tracking identifier e.g. KYC-2024-001', max_length=32, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Assignment'), ('ASSIGNED', 'Assigned to Officer'), ('APPROVED', 'Verified & Approved'), ('REJECTED', 'Rejected'), ('NEEDS_REVIEW', 'Needs Additional Review')], db_index=True, default='PENDING', max_length=20)),
                ('document_type', models.CharField(default='PAN & Aadhaar', max_length=80)),
                ('document_number', models.CharField(blank=True, max_length=50)),
                ('submitted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('assigned_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_kyc_requests', to='users.employee')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_requests', to='users.customer')),
                ('loan_application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kyc_requests', to='loans.loanapplication')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_kyc_requests', to='users.employee')),
            ],
            options={
                'verbose_name': 'KYC Verification Request',
                'verbose_name_plural': 'KYC Verification Requests',
                'db_table': 'finova_kyc_requests',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
