# Generated by Django 5.2.17 on 2026-09-28 05:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('account_number', models.CharField(max_length=24)),
                ('ifsc_code', models.CharField(max_length=11)),
                ('bank_name', models.CharField(max_length=100)),
                ('nickname', models.CharField(blank=True, max_length=60)),
                ('avatar_url', models.CharField(blank=True, max_length=255)),
                ('is_verified', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Transfer Beneficiary',
                'verbose_name_plural': 'Transfer Beneficiaries',
                'db_table': 'finova_beneficiaries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(db_index=True, help_text='Unique transaction reference (e.g. TXN20241110001)', max_length=36, unique=True)),
                ('beneficiary_name', models.CharField(max_length=120)),
                ('beneficiary_account', models.CharField(blank=True, max_length=24)),
                ('beneficiary_ifsc', models.CharField(blank=True, max_length=11)),
                ('transaction_type', models.CharField(choices=[('TRANSFER', 'Transfer (Internal/NEFT/RTGS/IMPS)'), ('DEBIT', 'Debit'), ('CREDIT', 'Credit'), ('DEPOSIT', 'Cash/Cheque Deposit'), ('WITHDRAWAL', 'Cash Withdrawal'), ('EMI_PAYMENT', 'Loan EMI Payment'), ('LOAN_DISBURSEMENT', 'Loan Disbursement')], db_index=True, default='TRANSFER', max_length=25)),
                ('category', models.CharField(choices=[('SHOPPING', 'Shopping & Electronics'), ('SALARY', 'Monthly Salary Credit'), ('EMI_BILLS', 'Auto-debit Loan EMI / Bills'), ('FOOD_DINING', 'Food & Dining'), ('UTILITIES', 'Utilities & Bills'), ('INVESTMENT', 'Interest Payout / Investment'), ('TRANSFER', 'UPI & Account Transfer'), ('OTHER', 'General Transactions')], db_index=True, default='TRANSFER', max_length=25)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Transaction value in INR', max_digits=12)),
                ('balance_after', models.DecimalField(blank=True, decimal_places=2, help_text='Account balance immediately following ledger commitment', max_digits=14, null=True)),
                ('status', models.CharField(choices=[('COMPLETED', 'Completed'), ('PENDING', 'Pending'), ('FAILED', 'Failed'), ('REVERSED', 'Reversed')], db_index=True, default='COMPLETED', max_length=15)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('reference_number', models.CharField(blank=True, max_length=64)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Banking Transaction',
                'verbose_name_plural': 'Banking Transactions',
                'db_table': 'finova_transactions',
                'ordering': ['-timestamp', '-id'],
            },
        ),
    ]
