# Generated by Django 5.2.17 on 2026-09-28 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('transactions', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiaries', to='users.customer'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='from_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debit_transactions', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='to_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_transactions', to='accounts.account'),
        ),
        migrations.AddConstraint(
            model_name='beneficiary',
            constraint=models.UniqueConstraint(fields=('customer', 'account_number', 'ifsc_code'), name='uniq_customer_beneficiary_account'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['from_account', 'timestamp'], name='idx_txn_from_time'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['to_account', 'timestamp'], name='idx_txn_to_time'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['category', 'timestamp'], name='idx_txn_cat_time'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['status', 'timestamp'], name='idx_txn_status_time'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='chk_transaction_amount_positive'),
        ),
    ]
