# Generated by Django 5.2.17 on 2026-09-28 05:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(db_index=True, help_text='e.g. USER_LOGIN, MONEY_TRANSFER, LOAN_APPROVED, KYC_VERIFIED', max_length=64)),
                ('ip_address', models.CharField(blank=True, max_length=45)),
                ('record_type', models.CharField(blank=True, max_length=64)),
                ('record_id', models.CharField(blank=True, max_length=64)),
                ('details', models.TextField()),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'finova_audit_logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
