# Generated by Django 5.2.17 on 2026-09-28 05:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_id', models.CharField(db_index=True, help_text='Unique facility reference e.g. HL-4091', max_length=32, unique=True)),
                ('principal_amount', models.DecimalField(decimal_places=2, help_text='Total sanctioned principal', max_digits=14)),
                ('interest_rate', models.DecimalField(decimal_places=2, help_text='Annual interest rate percentage', max_digits=5)),
                ('tenure_months', models.IntegerField()),
                ('monthly_emi', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_payable', models.DecimalField(decimal_places=2, max_digits=14)),
                ('total_interest', models.DecimalField(decimal_places=2, max_digits=14)),
                ('outstanding_amount', models.DecimalField(decimal_places=2, help_text='Remaining principal + accrued interest', max_digits=14)),
                ('repaid_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField()),
                ('next_due_date', models.DateField()),
                ('auto_debit', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved (Pending Disbursement)'), ('COMPLETED', 'Fully Repaid'), ('CLOSED', 'Closed'), ('DEFAULTED', 'Defaulted')], db_index=True, default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Credit Facility',
                'verbose_name_plural': 'Credit Facilities',
                'db_table': 'finova_loans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_id', models.CharField(db_index=True, help_text='Candidate key e.g. LA-2024-9182', max_length=32, unique=True)),
                ('requested_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tenure_months', models.IntegerField(help_text='Requested tenure in months')),
                ('proposed_interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('calculated_emi', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('purpose', models.CharField(max_length=255)),
                ('employment_type', models.CharField(max_length=50)),
                ('employer_name', models.CharField(blank=True, max_length=120)),
                ('monthly_income', models.DecimalField(decimal_places=2, max_digits=12)),
                ('existing_obligations', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('pan_number', models.CharField(max_length=10)),
                ('aadhaar_number', models.CharField(blank=True, max_length=16)),
                ('residential_address', models.CharField(max_length=255)),
                ('kyc_document_type', models.CharField(default='PAN & Salary Slip', max_length=50)),
                ('kyc_document_number', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='UNDER_REVIEW', max_length=20)),
                ('review_notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Loan Application',
                'verbose_name_plural': 'Loan Applications',
                'db_table': 'finova_loan_applications',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='LoanPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(db_index=True, max_length=36, unique=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('principal_component', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('interest_component', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('installment_number', models.IntegerField(default=1)),
                ('payment_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('SUCCESSFUL', 'Successful'), ('FAILED', 'Failed'), ('PENDING', 'Pending')], default='SUCCESSFUL', max_length=20)),
                ('receipt_number', models.CharField(max_length=40, unique=True)),
                ('remarks', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Loan Repayment',
                'verbose_name_plural': 'Loan Repayments',
                'db_table': 'finova_loan_payments',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='LoanType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='e.g. HOME, PERSONAL, EDUCATION, VEHICLE, BUSINESS', max_length=20, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('base_interest_rate', models.DecimalField(decimal_places=2, help_text='Base annual interest rate (e.g. 8.25)', max_digits=5)),
                ('min_amount', models.DecimalField(decimal_places=2, default=50000.0, max_digits=12)),
                ('max_amount', models.DecimalField(decimal_places=2, default=10000000.0, max_digits=12)),
                ('min_tenure_months', models.IntegerField(default=12)),
                ('max_tenure_months', models.IntegerField(default=360)),
                ('processing_fee_percent', models.DecimalField(decimal_places=2, default=0.5, max_digits=4)),
                ('description', models.TextField(blank=True)),
                ('icon_name', models.CharField(default='account_balance', max_length=40)),
            ],
            options={
                'verbose_name': 'Loan Product Type',
                'verbose_name_plural': 'Loan Product Types',
                'db_table': 'finova_loan_types',
            },
        ),
    ]
