# Generated by Django 5.2.17 on 2026-09-28 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('loans', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='users.customer'),
        ),
        migrations.AddField(
            model_name='loan',
            name='servicing_account',
            field=models.ForeignKey(help_text='Account from which monthly auto-debit EMI is deducted', on_delete=django.db.models.deletion.PROTECT, related_name='servicing_loans', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_applications', to='users.customer'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_loan_applications', to='users.employee'),
        ),
        migrations.AddField(
            model_name='loan',
            name='application',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sanctioned_loan', to='loans.loanapplication'),
        ),
        migrations.AddField(
            model_name='loanpayment',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loan_payments', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='loanpayment',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='loans.loan'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='loan_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='loans.loantype'),
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='loans.loantype'),
        ),
        migrations.AddIndex(
            model_name='loanpayment',
            index=models.Index(fields=['loan', 'payment_date'], name='idx_loan_pmt_date'),
        ),
        migrations.AddIndex(
            model_name='loanapplication',
            index=models.Index(fields=['customer', 'status'], name='idx_loan_app_cust_status'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['customer', 'status'], name='idx_loan_cust_status'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['next_due_date'], name='idx_loan_due_date'),
        ),
        migrations.AddConstraint(
            model_name='loan',
            constraint=models.CheckConstraint(condition=models.Q(('outstanding_amount__gte', 0)), name='chk_loan_outstanding_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='loan',
            constraint=models.CheckConstraint(condition=models.Q(('principal_amount__gt', 0)), name='chk_loan_principal_positive'),
        ),
    ]
