# Generated by Django 5.2.17 on 2026-09-28 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='e.g., SAVINGS, CURRENT, FD', max_length=20, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('interest_rate_pa', models.DecimalField(decimal_places=2, default=4.0, help_text='Annual interest rate percentage', max_digits=5)),
                ('minimum_balance', models.DecimalField(decimal_places=2, default=1000.0, max_digits=12)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Account Type',
                'verbose_name_plural': 'Account Types',
                'db_table': 'finova_account_types',
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(db_index=True, help_text='Standard 12 to 16-digit Indian bank account number', max_length=16, unique=True)),
                ('available_balance', models.DecimalField(decimal_places=2, default=0.0, help_text='Current liquid balance available for withdrawal/transfer', max_digits=14)),
                ('ledger_balance', models.DecimalField(decimal_places=2, default=0.0, help_text='Total book balance including uncleared items', max_digits=14)),
                ('currency', models.CharField(default='INR', max_length=5)),
                ('card_variant', models.CharField(default='RuPay Platinum Contactless', max_length=50)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('FROZEN', 'Frozen'), ('DORMANT', 'Dormant'), ('CLOSED', 'Closed')], db_index=True, default='ACTIVE', max_length=20)),
                ('is_primary', models.BooleanField(default=False)),
                ('opened_date', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='branches.branch')),
            ],
            options={
                'verbose_name': 'Customer Account',
                'verbose_name_plural': 'Customer Accounts',
                'db_table': 'finova_accounts',
                'ordering': ['-is_primary', 'id'],
            },
        ),
    ]
