# Generated by Django 5.2.17 on 2026-09-28 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_code', models.CharField(help_text='Unique branch identifier code (e.g., BLR01, MUM02)', max_length=10, unique=True)),
                ('branch_name', models.CharField(max_length=120)),
                ('ifsc', models.CharField(db_index=True, help_text='11-character Indian Financial System Code (e.g., FINO0001234)', max_length=11, unique=True)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(db_index=True, max_length=80)),
                ('state', models.CharField(max_length=80)),
                ('pincode', models.CharField(max_length=10)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('manager_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Bank Branch',
                'verbose_name_plural': 'Bank Branches',
                'db_table': 'finova_branches',
                'ordering': ['branch_code'],
            },
        ),
    ]
